default_platform(:ios)

platform :ios do
  desc "Build Flutter project"
  lane :build do

    Dir.chdir("..") do
      sh("flutter", "build", "ios")
    end

    Dir.chdir("../ios") do
      cocoapods(podfile: "./ios/Podfile")
      build_app(scheme: "Runner", workspace: "./ios/Runner.xcworkspace", export_method: "development", export_options: {"provisioningProfiles" => {"dev.flutter.VeggieSeasons"=> "BitriseBot-Wildcard"}, "method"=> "development", "signingStyle" => "manual", "signingCertificate"=> "iPhone Developer: Dev Portal Bot Bitrise"})
    end

    Dir.chdir("../android") do
      build_android_app(task: "assemble", flavor: "Release", project_dir: "./android", gradle_path: "./gradlew")
    end
  end
end
